import { CartProvider } from "./addtocart/cartContext";
import { Toaster } from "@/components/ui/toaster"
import { Montserrat } from "next/font/google";
import { Poppins } from "next/font/google";
import type { Metadata } from "next";
import { WishlistProvider } from "./wishlist/wishlistContext";
import Link from "next/link";
import "./globals.css";

const fontMontserrat = Montserrat({ subsets: ["latin"],
  weight: ['700']
 }
);

const fontPoppins = Poppins({ subsets: ['latin'],
  weight: ['500']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
          <WishlistProvider>
        {/* Header */}
        <header className="w-full fixed z-10 h-[100px] bg-[#FFFF] flex items-center max-mt:h-[180px]">
          <div className="w-full h-[41px] flex flex-row items-center justify-around max-mt:h-[180px] max-mt:flex-col">

            <div className="w-[290px] h-[41px] gap-[5px] flex flex-row items-center max-2xl:w-[230px] max-lg:h-[49px] max-mt:w-[185px]">
              <img className="w-[52px] h-[56px] max-2xl:w-[44px] max-2xl:h-[44px] max-lt:w-[32px] max-lt:h-[32px] max-mt:w-[40px] max-mt:h-[40px]" src="/mybrandlogo.png" alt="mainlogo"/>
              <div className={fontMontserrat.className}>
               <h1 className="text-[#000000] text-[34px] w-[234px] h-[41px] max-2xl:w-[178px] max-2xl:text-[30px] max-xl:text-[26px] max-lg:text-[24px] max-lt:h-[32px] max-lt:text-[20px] max-mt:w-[140px]">ShopCatalog</h1>
              </div>
            </div>


            <div className={fontPoppins.className}>
              <ul className="w-[430px] h-[24px] flex flex-row gap-[48px] justify-center max-lg:w-[400px] max-lg:gap-[36px] max-lt:w-[300px] max-lt:gap-[28px] max-mt:gap-[36px] max-sm:gap-[26px]">
                <Link href={`/`}><li className="w-[48px] h-[24px] text-[16px] text-[#000000] cursor-pointer hover:text-red-600">Home</li></Link>
                <Link href={`/shopSection`}><li className="w-[42px] h-[24px] text-[16px] text-[#000000] cursor-pointer hover:text-red-600">Shop</li></Link>
                <Link href={`/blogSection`}><li className="w-[36px] h-[24px] text-[16px] text-[#000000] cursor-pointer hover:text-red-600">Blog</li></Link>
                <Link href={`/contactSection`}><li className="w-[66px] h-[24px] text-[16px] text-[#000000] cursor-pointer hover:text-red-600">Contact</li></Link>
              </ul>
            </div>

            <div className="flex flex-row gap-[48px] items-center max-lg:gap-[36px] max-lt:gap-[28px] max-mt:mb-[18px] max-mt:gap-[48px] max-sm:gap-[36px]">
              <div className="w-[28px] h-[24px]">
                <Link href={`/login`}>
                  <img className="w-[23.3px] h-[18.6px] cursor-pointer" src="/navbarlogo/logoOne.png" alt="logoOne" />
                </Link>               
              </div>
              <div className="w-[28px] h-[24px]">
                <img className="w-[22.1px] h-[22.1px] cursor-pointer" src="/navbarlogo/logoTwo.png" alt="logoTwo"/>
              </div>
              <div className="w-[28px] h-[24px]">
                <Link href={`/wishlistSection`}>
                  <img className="w-[23.3px] h-[20.8px] cursor-pointer" src="/navbarlogo/logoThree.png" alt="logoThree"/>
                </Link>              
              </div>
              <div className="w-[28px] h-[24px]">
                <Link href={`/cartSection`}>
                  <img className="w-[24.5px] h-[22.6px] cursor-pointer" src="/navbarlogo/logoFour.png" alt="logoFour"/>
                </Link>
              </div>
            </div>

          

          </div>
        </header>
        {children}
       
      <div className={fontPoppins.className}>
        <footer className="h-[400px] mt-[32px] max-lt:h-[500px] max-mt:h-[475px] max-st:h-[910px]">
          <div className="h-[370px] flex flex-col max-lt:h-[450px] max-st:h-[876px]">
            <div className="h-[312px] flex flex-row justify-evenly max-lt:h-[400px] max-lt:flex-col max-lt:items-center max-lt:gap-[48px] max-st:h-[820px] max-st:gap-[16px]">
              <div className="flex flex-col justify-evenly max-lt:flex-row max-lt:gap-[32px] max-lt:items-center max-st:flex-col max-st:mb-[20px]">
                <h2 className="w-[170px] h-[36px] font-bold text-[24px] text-[#000000]">ShopCatalog</h2>
                <p className="w-[285px] h-[72px] font-normal text-[16px] text-[#9F9F9F] max-lg:w-[225px] max-lt:w-full max-lt:h-[26px] max-lm:w-[360px] max-lm:h-[51px] max-mm:w-[320px] max-lm:text-center max-sm:w-[300px]">400 University Drive Suite 200 Coral Gables,
                FL 33134 USA</p>
              </div>
              <div className="flex flex-row gap-[64px] max-lg:gap-[48px] max-st:flex-col max-st:items-center max-st:gap-[24px]">
                <div className="flex flex-col gap-[36px] max-st:text-center">        
                  <p className="w-[72px] h-[24px] font-medium text-[16px] text-[#9F9F9F]">Links</p>
                  <div className="w-[72px] h-[233px] flex flex-col gap-[24px] max-st:h-[200px]">
                    <p className="w-[72px] h-[24px] font-medium text-[16px] hover:text-red-700 cursor-pointer">Home</p>
                    <p className="w-[72px] h-[24px] font-medium text-[16px] hover:text-red-700 cursor-pointer">Shop</p>
                    <p className="w-[72px] h-[24px] font-medium text-[16px] hover:text-red-700 cursor-pointer">About</p>
                    <p className="w-[72px] h-[24px] font-medium text-[16px] hover:text-red-700 cursor-pointer">Contact</p>
                  </div>   
                </div>
                <div className="flex flex-col gap-[36px] max-st:text-center">        
                  <p className="w-[140px] h-[24px] font-medium text-[16px] text-[#9F9F9F]">Helps</p>
                  <div className="w-[140px] h-[242px] flex flex-col gap-[24px] max-st:h-[155px]">
                    <p className="w-[140px] h-[24px] font-medium text-[16px] hover:text-red-700 cursor-pointer">Payment Option</p>
                    <p className="w-[140px] h-[24px] font-medium text-[16px] hover:text-red-700 cursor-pointer">Returns</p>
                    <p className="w-[140px] h-[24px] font-medium text-[16px] hover:text-red-700 cursor-pointer">Privacy Policies</p>
                  </div>   
                </div>
                <div className="h-[78px] flex flex-col justify-between">
                  <p className="w-[86px] h-[24px] font-medium text-[16px] text-[#9F9F9F]">Newsletter</p>
                  <div className="w-[300px] h-[24px] flex flex-row gap-[24px]">
                    <p className="w-[194px] h-[21px] font-normal text-[14px] text-[#9F9F9F] underline">Enter Your Email Address</p>
                    <p className="w-[75px] h-[21px] font-medium text-[14px] text-[#000000] underline hover:text-red-700 cursor-pointer">SUBSCRIBE</p>
                  </div>
                </div>
              </div>
            </div>
            <hr className="border bg-[#D9D9D9]"/>
            <div className="w-full h-[24px] flex flex-col items-center mt-[32px] max-st:text-center">
              <p className="w-[325px] h-[24px] font-normal text-[16px] text-[#000000]">2023 ShopCatalog. All rights reverved</p>
            </div>
          </div>
        </footer>

      </div>
       </WishlistProvider>
      </CartProvider>
      <Toaster />
      </body>
    </html>
  );
}
